### ISSUE TITLE
Dependency problem during install

### ISSUE THREAD

**Issue by dsoprea** [awakesecurity/language-ninja#15]
I'm installing on Ubuntu 14.04 but it seems like Cabal doesn't like any of the available versions of Haskell for the requirement even though the versions appear to fall within the range. What am I doing wrong?

```
$ cabal install
Warning: language-ninja.cabal: Ignoring unknown section type: custom-setup
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: language-ninja-0.1.0
rejecting: base-4.6.0.1/installed-8aa... (conflict: language-ninja =>
base>=4.8 && <5.0)
rejecting: base-4.10.0.0, 4.9.1.0, 4.9.0.0, 4.8.2.0, 4.8.1.0, 4.8.0.0,
4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0,
4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0,
3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
```

**Comment by Gabriella439** [comment]
What this error message means is that your version of `ghc` has the `base-4.6.0.1` package installed (i.e. version `4.6.0.1` of the `base` package), but `language-ninja` only builds against `base-4.8` or higher.  This isn't an error in your setup and it's fixable in `language-ninja`.  This is usually just a matter of lowering the lower bound on the `base` dependency

You can actually test this quickly on your end by doing the following:

```
$ cabal get language-ninja
$ cd language-ninja-0.1.0/
```

... then modify the `language-ninja.cabal` file to replace all occurrences of this:

```
base                        >= 4.8   && < 5.0
```

... with this:

```
base                        >= 4.6   && < 5.0
```

... and then doing `cabal build` to see if it installs successfully.  If it does then we can make that change permanent and upload the new lower bound on `base` to Hackage

cc: @taktoa: You might try using https://github.com/hvr/multi-ghc-travis to test that `language-ninja` builds with older versions of `ghc`/`cabal`.  It's amazing for catching these sorts of compatibility issues for older installations.  I think you only need to check back to GHC 7.10.3, which is what the latest Ubuntu LTS release (Xenial) uses

**Comment by taktoa** [comment]
I [set up](https://github.com/awakesecurity/language-ninja/commit/f66e08873509d946bc8f6ffbc87f77923699c573) some Hydra jobs for GHC 7.10.3, GHC 8.0.2, and GHC 8.2.1; I'll fix any bugs found by these builds.

**Comment by taktoa** [comment]
GHC 7.10 support is blocked on `monad-mock` being fixed for 7.10: https://github.com/cjdev/monad-mock/issues/1

**Comment by lexi-lambda** [comment]
I’ve uploaded a new release of `monad-mock` that supports GHC 7.10, so `language-ninja` should now already build fine on GHC 7.10 (since it’s only a patch-level version bump). Unfortunately, it looks like @dsoprea’s installation is even older; judging by the error message, it’s GHC 7.6. GHC 7.6.2 is four and a half years old, and I am reluctant to do a lot of work to support it. Unless there is a very compelling reason to support that far back, I think it would be easier to just upgrade your GHC.

**Comment by Gabriella439** [comment]
Yeah, I think supporting the latest LTS release of Ubuntu is enough and that uses GHC 7.10.3

**Comment by taktoa** [comment]
@dsoprea

I just released [`language-ninja-0.2.0`](https://hackage.haskell.org/package/language-ninja-0.2.0), which should build under GHC 7.10.3 (though you should remember to `cabal update` to make `cabal` aware of the new `monad-mock` version).

If you want to get GHC 7.10.3, you have a few options:
- Update to the latest Ubuntu LTS (Xenial).
- Use `stack` (though I am not sure if I would need to add a `stack.yaml` for this to work).
- Use [Nix](https://nixos.org/nix). I don't think any version of nixpkgs has `language-ninja`, so you'd need to [add a Haskell package "override"](https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure). I can elaborate more on this if you are interested.

**Comment by dsoprea** [comment]
We'll see. I'll probably have to make the hack.

Our policy only prescribes 14.04 for development, for now.

Note that any company that only deploys LTS might very well be more than a
year behind on the LTS versions. That's the point of using LTS.

Thanks, guys.

**Comment by Gabriella439** [comment]
@dsoprea: keep in mind that if you use `stack` then you can easily have the latest version of `ghc` regardless of what your Ubuntu distribution provides
