### ISSUE TITLE
Release version 0.1.0 to Hackage

### ISSUE THREAD

**Issue by taktoa** [awakesecurity/language-ninja#2]
Release checklist:
- [x] Library:
  - [x] Address all `FIXME` comments.
  - [x] Full documentation.
  - [x] Add `@since` annotations to all public functions.
  - [x] Get the code to be clean with respect to `-Weverything`.
  - [x] Remove unneeded dependencies.
- [x] Tests:
  - [x] Set up `doctest`.
  - [x] Test all optics with `tasty-lens`.
  - [x] Remove unneeded dependencies.
- [x] Executables:
  - [x] Move `ninja2nix` into a separate project.
  - [x] Write executables:
    - [x] `ninja-lex`
    - [x] `ninja-parse`
    - [x] `ninja-evaluate`
  - [x] Proper command-line interface for any executables.
  - [x] Remove unneeded dependencies.
- [ ] Blockers:
  - [ ] `smallcheck-lens` and `tasty-lens` need `base` version bumps.
    - [ ] jdnavarro/smallcheck-lens#4
    - [ ] jdnavarro/tasty-lens#1
- [x] Miscellaneous:
  - [x] Add `README.md` et al. to `extra-*-files`
  - [x] Add `.github/CONTRIBUTING.md`
  - [x] Add changelog section to Cabal file.
  - [x] Signed `git` tag (non-lightweight) at the appropriate version.

**Comment by Gabriel439** [comment]
Don't forget to add documentation to the checklist, such as:

* 100% haddock coverage
* Tutorial
* Announcement post

**Comment by taktoa** [comment]
https://hackage.haskell.org/package/language-ninja-0.1.0
