### ISSUE TITLE
Switch parser over to `megaparsec`

### ISSUE THREAD

**Issue by taktoa** [awakesecurity/language-ninja#4]
The current lexer/parser is well-optimized, but it is unclear that it is correct. We should have another parser, written using `megaparsec`, that is more obviously correct and easier to test. This also requires adding polymorphic annotation fields to all the datatypes. For example, this datatype:

```
data Foo = MkFoo { _fooBar :: Bar, _fooBaz :: Baz }
```

would become this datatype:

```
data Foo ann = MkFoo { _fooAnn :: ann, _fooBar :: Bar, _fooBaz :: Baz }
instance Annotated Foo where { ... }
```

where `Annotated` is defined by:

```
class (Functor t) => Annotated (t :: * -> *) where
  annotation :: Lens' (t ann) ann
```

The old, fast parser would then have type `Text -> Parser (PNinja ())`, whereas the new `megaparsec` parser would have type `Text -> Parser (PNinja (Maybe Pos))`, for example. This would allow pretty-printing such that the output is identical to the parsed input, which is important for diagnostics, testing, and formatting tools.

**Comment by Gabriella439** [comment]
I'd recommend switching to the `parsers` library so that you can use multiple parser backends (like `trifecta` for nicer error messages, for example)

**Comment by taktoa** [comment]
I haven't implemented this parser yet, so `parsers` is still an option, but it is important that the parser library support something like [`getPosition`](https://hackage.haskell.org/package/megaparsec-5.3.0/docs/Text-Megaparsec-Prim.html#v:getPosition), and it must also support indentation-sensitive parsing (though in the worst case this can be reconstructed from `getPosition`).

**Comment by taktoa** [comment]
The lexer now uses Megaparsec, so I'm closing this.
