### ISSUE TITLE
Consider using `Control.Exception.Lens` instead of `ether`

### ISSUE THREAD

**Issue by Gabriella439** [awakesecurity/language-ninja#6]
`Control.Exception.Lens` provides a nice approach for modeling exception subtyping using prisms.  Instead of an `ether` type like this:

```haskell
(MonadExcept IOException m, MonadException CompileError m) => ...
```

... you would have:

```haskell
(AsIOException e, AsCompileError e, MonadException e m) => ...
```

See this thread for more details:

https://www.reddit.com/r/haskell/comments/2utxua/prisms_and_monaderrors/?st=j4aqwbyx&sh=1c57491b

... and:

https://hackage.haskell.org/package/lens-4.15.3/docs/Control-Exception-Lens.html

**Comment by taktoa** [comment]
I ended up using [`MonadError`](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Error-Class.html) from `mtl`.
